kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: test
    image: node
    commands:
      - npm install
      - npm run build
      - npm run test
    when:
      status:
        - failure
        - success
