kind: pipeline
name: default

steps:
  - name: run-tests
    image: node:10.16.0
    commands:
      - npm run build
      - npm run test
    when:
      status:
        - failure
        - success
      event:
        - pull_request
      branch:
        - master
        - "*:master"
