kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: node
    commands:
      - npm install
      - npm run build
      - npm run test
    when:
      status:
        - failure
        - success
      event:
        - pull_request
      branch:
        - master
        - "*:master"
